name: "Neurodiversity in Design"
description: "Neurodiversity in Design European Working Group"

url: "http://neurodiversityindesign.org"

paginate: 10

markdown: kramdown
highlighter: rouge
permalink: pretty

exclude: []
